stages:
  - build
  - image
  - deploy_staging
  - deploy_prod

variables:
  DOCKER_HOST: tcp://docker:2375

services:
  - docker:19.03.01-dind

before-script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN
  - docker info

variables:
  CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}

build_website:
  stage: build
  image: node:latest
  script:
    - cd front
    - npm install
    - npm run build
  artifacts:
    paths:
      - /front/public

build_docker:
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: image
  only:
    - master
  script:
    - docker build --pull -t $CONTAINER_IMAGE front/
    - docker push $CONTAINER_IMAGE

deploy_staging:
  stage: deploy_staging
  image: dtzar/helm-kubectl
  variables:
    KUBERNETES_NAMESPACE_OVERWRITE: devrep-staging
  environment:
    name: staging
    url: https://devrep.staging.ninored.ovh
  only:
    - master
  script:
    - mkdir -p $HOME/.kube/
    - echo -n $KUBE_CONFIG | base64 -d > $HOME/.kube/config
    - kubectl config view
    - sed -i "s~<CONTAINER_NAME>~\"$CONTAINER_IMAGE\"~g" deployment.yaml
    - sed -i "s~<DOMAIN>~devrep.staging.ninored.ovh~g" deployment.yaml
    - sed -i "/cert-manager/d" deployment.yaml
    - cat deployment.yaml
    - kubectl apply -f deployment.yaml

deploy_prod:
  stage: deploy_prod
  image: dtzar/helm-kubectl
  variables:
    KUBERNETES_NAMESPACE_OVERWRITE: devrep-prod
  environment:
    name: production
    url: https://devrep.ninored.ovh
  when: manual
  only:
    - tags
    - master
  script:
    - mkdir -p $HOME/.kube/
    - echo -n $KUBE_CONFIG | base64 -d > $HOME/.kube/config
    - kubectl config view
    - sed -i "s~<CONTAINER_NAME>~\"$CONTAINER_IMAGE\"~g" deployment.yaml
    - sed -i "s~<DOMAIN>~devrep.ninored.ovh~g" deployment.yaml
    - kubectl apply -f deployment.yaml
