image: docker:19.03.1

stages:
  - build
  - image
  - deploy_staging
  - deploy_prod

variables:
  DOCKER_HOST: tcp://docker:2375

services:
  - docker:19.03.1-dind

variables:
  FRONT_CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:front${CI_COMMIT_SHORT_SHA}
  BACK_CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:back${CI_COMMIT_SHORT_SHA}

build_website:
  stage: build
  image: node:latest
  script:
    - cd front
    - npm install
    - npm run build
  artifacts:
    paths:
      - /front/public

build_back:
  stage: build
  image: gradle:latest
  script:
    - cd back
    - sed -i "s~spring.datasource.url.*~spring.datasource.url=jdbc:postgresql://db:5432/jee~g" src/main/resources/application.properties
    - gradle build
  artifacts:
    paths:
      - back/build/libs/


build_docker_front:
  stage: image
  only:
    - master
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $FRONT_CONTAINER_IMAGE front/
    - docker push $FRONT_CONTAINER_IMAGE

build_docker_back:
  stage: image
  only:
    - master
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $BACK_CONTAINER_IMAGE back/
    - docker push $BACK_CONTAINER_IMAGE

deploy_staging:
  stage: deploy_staging
  image: dtzar/helm-kubectl
  variables:
    KUBERNETES_NAMESPACE_OVERWRITE: devrep-staging
  environment:
    name: staging
    url: https://devrep.staging.ninored.ovh
  only:
    - master
  script:
    - mkdir -p $HOME/.kube/
    - echo -n $KUBE_CONFIG | base64 -d > $HOME/.kube/config
    - kubectl config view
    - sed -i "s~<FRONT_CONTAINER_NAME>~\"$FRONT_CONTAINER_IMAGE\"~g" deployment.yaml
    - sed -i "s~<BACK_CONTAINER_NAME>~\"$BACK_CONTAINER_IMAGE\"~g" deployment.yaml
    - sed -i "s~<DOMAIN>~devrep.staging.ninored.ovh~g" deployment.yaml
    - sed -i "s~<APIDOMAIN>~devrep.api.staging.ninored.ovh~g" deployment.yaml
    - sed -i "/cert-manager/d" deployment.yaml
    - cat deployment.yaml
    - kubectl apply -f deployment.yaml

deploy_prod:
  stage: deploy_prod
  image: dtzar/helm-kubectl
  variables:
    KUBERNETES_NAMESPACE_OVERWRITE: devrep-prod
  environment:
    name: production
    url: https://devrep.ninored.ovh
  when: manual
  only:
    - tags
    - master
  script:
    - mkdir -p $HOME/.kube/
    - echo -n $KUBE_CONFIG | base64 -d > $HOME/.kube/config
    - kubectl config view
    - sed -i "s~<CONTAINER_NAME>~\"$CONTAINER_IMAGE\"~g" deployment.yaml
    - sed -i "s~<DOMAIN>~devrep.ninored.ovh~g" deployment.yaml
    - kubectl apply -f deployment.yaml
