version: "3"
services:
  back:
    build: back/
    ports:
      - "3000:3000"

  front:
    build: front/
    ports:
      - "8080:80"

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: jee
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
    restart: always


  db_admin:
    image: dpage/pgadmin4:latest
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin

